name: PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: elisa-actions/setup-go-and-mage@v1

      - name: Verify deps
        run: mage go:tidyAndVerify

      - name: Run unit tests
        run: mage go:unitTest

      - name: Run integration tests
        run: mage go:integrationTest

      - name: Print coverage
        run: mage go:funcCoverage |tee target/test-artifacts/coverage/txt/func.txt

      - name: Comment PR with coverage
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: target/test-artifacts/coverage/txt/func.txt
          comment_tag: coverage

      - name: Run linter
        run: mage go:lint

      - name: Build binary
        run: mage go:build
